version: "3"

services:
  postgres:
    container_name: medusajs-postgres
    image: postgres
    network_mode: host
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medusa-db
    volumes:
      - postgres:/app/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 2s

  backend:
    container_name: medusajs-backend
    image: jmflaherty/medusajs-backend
    network_mode: host
    tty: true
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/medusa-db
      - STORE_CORS=http://localhost:8080
      - ADMIN_CORS=http://localhost:7000
    volumes:
      - backend:/app/
    depends_on:
      postgres:
        condition: service_healthy

  admin:
    container_name: medusajs-admin
    image: jmflaherty/medusajs-admin
    network_mode: host
    tty: true
    environment:
      - MEDUSA_BACKEND_URL=http://localhost:9000
    volumes:
      - admin:/app/
    depends_on:
      backend:
        condition: service_healthy

  frontend:
    container_name: medusajs-frontend
    image: jmflaherty/medusajs-frontend
    network_mode: host
    tty: true
    environment:
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://localhost:9000
    volumes:
      - frontend:/app/
    depends_on:
      backend:
        condition: service_healthy

  playwright:
    container_name: medusajs-playwright
    build:
      context: .
    profiles:
      - playwright
    network_mode: host
    tty: true
    environment:
      - STORE_URL=http://localhost:8080
    volumes:
      - playwright:/app/
    depends_on:
      frontend:
        condition: service_healthy

volumes:
  postgres:
  backend:
  admin:
  frontend:
  playwright:
