name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    branches: [main, master]

jobs:
  playwright:
    name: Run Playwright
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: medusa-db
        ports:
          - 5432:5432
      backend:
        image: jmflaherty/medusajs-backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/medusa-db
          STORE_CORS: http://localhost:8080
          ADMIN_CORS: http://localhost:7000
        ports:
          - 9000:9000
      admin:
        image: jmflaherty/medusajs-admin
        ports:
          - 7000:7000
      frontend:
        image: jmflaherty/medusajs-frontend
        ports:
          - 8080:8080

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
